# network
network-id="1337"

# gas -- uncomment line below for gas free network
min-gas-price=0

# data
genesis-file="/config/genesis.json"
node-private-key-file="/opt/besu/keys/nodekey"
logging="INFO"
data-path="/opt/besu/data"
host-allowlist=["*"]

# p2p
# p2p-host="<REPLACE_ME>"
# p2p-port="<REPLACE_ME>"
# max-peers=25

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3", "QBFT", "CLIQUE", "EEA", "IBFT"]
rpc-http-cors-origins=["all"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3", "QBFT", "CLIQUE", "EEA", "IBFT"]

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["all"]

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# privacy
# privacy-enabled=true
# privacy-url="http://<HOST>:<PORT>"
# privacy-public-key-file=""

# permissions
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/config/permissions-config.toml"


# bootnodes
bootnodes=["enode://c892d4fe022abc5457cb2c8613581af6a5ef98d1b20fbbef8c926754d9757402ed4779b05ca0a39bb4078d35e841de63f4ee90fb6e71b22bf8a6d357eb45e985@172.16.239.11:30303"]

# static nodes
static-nodes-file="/config/static-nodes.json"
discovery-enabled=true
# miner-enabled=true
